from __future__ import annotations

"""Optional AI executive-summary support for PCAPCase reports.

This module is intentionally safe-by-default:
- It performs no network calls during import.
- It imports no provider SDKs during import.
- It reads no API keys while building a redacted payload.
- It never accepts API keys from CLI arguments or config files.

The only data allowed into the AI payload is a minimized, redacted summary of
findings: title, severity, confidence, category, and redacted evidence excerpts.
Raw PCAP bytes, extracted objects, packet payloads, and unredacted findings must
never be passed to providers.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal
import json

from .redaction import Redactor, load_redaction_rules

ProviderName = Literal["anthropic", "openai"]

AI_SUMMARY_SECTION_HEADING = "## AI-Generated Summary (optional)"
AI_SUMMARY_DISCLAIMER = (
    "Generated by an optional external AI provider from redacted finding "
    "metadata only; this text is not part of the evidence chain."
)
AI_SYSTEM_PROMPT = (
    "You are assisting with a network-forensics report. Write one short "
    "executive-summary paragraph based only on the redacted finding metadata "
    "provided. Do not invent facts, indicators, hosts, attribution, malware "
    "families, impact, or remediation steps that are not present in the input."
)


@dataclass(frozen=True)
class RedactedEvidenceExcerpt:
    frame_number: int | None
    protocol: str | None
    field: str
    value: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "frame_number": self.frame_number,
            "protocol": self.protocol,
            "field": self.field,
            "value": self.value,
        }


@dataclass(frozen=True)
class RedactedFindingSummary:
    title: str
    severity: str
    confidence: str
    category: str
    evidence_excerpts: tuple[RedactedEvidenceExcerpt, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "severity": self.severity,
            "confidence": self.confidence,
            "category": self.category,
            "evidence_excerpts": [excerpt.to_dict() for excerpt in self.evidence_excerpts],
        }


@dataclass(frozen=True)
class AISummaryPayload:
    """Minimal provider payload derived from redacted findings only."""

    schema_version: str
    findings: tuple[RedactedFindingSummary, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "findings": [finding.to_dict() for finding in self.findings],
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)


class AISummaryProvider(ABC):
    """Provider-agnostic interface for optional AI summaries.

    Implementations may import provider SDKs lazily inside their constructors or
    methods, but importing this module must not load SDKs or make network code
    reachable by default CLI/report behavior.
    """

    name: ProviderName
    required_env_var: str

    @abstractmethod
    def generate_summary(self, payload: AISummaryPayload) -> str:
        """Return a plain-text executive-summary paragraph.

        Implementations must treat the provider response as untrusted plain text.
        The returned text is embedded in report.md only; it must never be
        executed, parsed as commands, or written to manifests with secrets.
        """


def build_redacted_payload_from_findings_file(
    findings_path: str | Path,
    redaction_rules_path: str | Path | None = None,
    max_findings: int = 25,
    max_evidence_per_finding: int = 3,
    max_excerpt_chars: int = 240,
) -> AISummaryPayload:
    """Load findings.json and build the minimized redacted AI payload.

    The input is expected to be PCAPCase's `findings.json` list. Any unknown or
    additional keys are ignored on purpose, so raw packet payloads, host lists,
    extracted object paths, recommendations, reproduction commands, and case
    manifests are excluded from the external payload.
    """

    path = Path(findings_path)
    findings_data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(findings_data, list):
        raise ValueError(f"findings.json must contain a list: {path}")
    return build_redacted_payload(
        findings_data,
        redaction_rules_path=redaction_rules_path,
        max_findings=max_findings,
        max_evidence_per_finding=max_evidence_per_finding,
        max_excerpt_chars=max_excerpt_chars,
    )


def build_redacted_payload(
    findings: list[dict[str, Any]],
    redaction_rules_path: str | Path | None = None,
    max_findings: int = 25,
    max_evidence_per_finding: int = 3,
    max_excerpt_chars: int = 240,
) -> AISummaryPayload:
    """Build a provider-safe payload from already-generated findings.

    Allowed outbound fields per finding:
    - title
    - severity
    - confidence
    - category
    - redacted evidence excerpts containing frame number, protocol, field, value

    Everything else is deliberately dropped. Redaction is applied even if the
    report pipeline already redacted the finding, creating a second safety pass
    before any optional provider call.
    """

    redactor = Redactor(load_redaction_rules(redaction_rules_path))
    normalized: list[RedactedFindingSummary] = []
    for finding in findings[:max_findings]:
        if not isinstance(finding, dict):
            continue
        evidence_items = finding.get("evidence", [])
        if not isinstance(evidence_items, list):
            evidence_items = []
        excerpts: list[RedactedEvidenceExcerpt] = []
        for evidence in evidence_items[:max_evidence_per_finding]:
            if not isinstance(evidence, dict):
                continue
            field = _clean_text(evidence.get("field"), redactor, max_excerpt_chars)
            value = _clean_text(evidence.get("value"), redactor, max_excerpt_chars)
            excerpts.append(
                RedactedEvidenceExcerpt(
                    frame_number=_optional_int(evidence.get("frame_number")),
                    protocol=_optional_text(evidence.get("protocol"), redactor, 32),
                    field=field,
                    value=value,
                )
            )
        normalized.append(
            RedactedFindingSummary(
                title=_clean_text(finding.get("title"), redactor, 160),
                severity=_clean_text(finding.get("severity"), redactor, 32),
                confidence=_clean_text(finding.get("confidence"), redactor, 32),
                category=_clean_text(finding.get("category"), redactor, 80),
                evidence_excerpts=tuple(excerpts),
            )
        )
    normalized.sort(key=lambda item: (item.severity, item.category, item.title))
    return AISummaryPayload(schema_version="1", findings=tuple(normalized))


def append_ai_summary_to_markdown(report_path: str | Path, summary: str) -> None:
    """Append an AI summary section to report.md as plain Markdown text."""

    path = Path(report_path)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    safe_summary = _plain_text_summary(summary)
    section = (
        f"\n\n{AI_SUMMARY_SECTION_HEADING}\n\n"
        f"> {AI_SUMMARY_DISCLAIMER}\n\n"
        f"{safe_summary}\n"
    )
    if AI_SUMMARY_SECTION_HEADING in existing:
        before = existing.split(AI_SUMMARY_SECTION_HEADING, 1)[0].rstrip()
        path.write_text(before + section, encoding="utf-8")
    else:
        path.write_text(existing.rstrip() + section, encoding="utf-8")


def transparency_banner(provider: ProviderName) -> str:
    return (
        f"[!] Optional AI summary enabled for provider: {provider}\n"
        "[!] Data sent externally: finding titles, severities, confidences, "
        "categories, and redacted evidence excerpts only.\n"
        "[!] Data not sent: raw PCAP, packet payloads, extracted files, API keys, "
        "full reports, manifests, or unredacted findings."
    )


def _clean_text(value: Any, redactor: Redactor, max_chars: int) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\r", " ").replace("\n", " ").strip()
    text = redactor.redact(text)
    if len(text) > max_chars:
        return text[: max_chars - 1].rstrip() + "…"
    return text


def _optional_text(value: Any, redactor: Redactor, max_chars: int) -> str | None:
    text = _clean_text(value, redactor, max_chars)
    return text or None


def _optional_int(value: Any) -> int | None:
    try:
        return int(value) if value is not None and value != "" else None
    except (TypeError, ValueError):
        return None


def _plain_text_summary(summary: str) -> str:
    text = str(summary).replace("\r\n", "\n").replace("\r", "\n").strip()
    # Keep the provider response as inert prose. Backticks are escaped to avoid
    # accidentally creating executable-looking Markdown code blocks.
    text = text.replace("```", "` ` `")
    return text
