from __future__ import annotations

import json
import os
import urllib.request
import urllib.error
from pathlib import Path

VT_API_BASE = "https://www.virustotal.com/api/v3"
DEFAULT_SYNC_DIR = Path.home() / ".pcapcase" / "vt"


class VTSyncError(RuntimeError):
    pass


def get_api_key() -> str:
    key = os.environ.get("VT_API_KEY")
    if not key:
        raise VTSyncError(
            "VT_API_KEY environment variable is not set. "
            "Please set it using: export VT_API_KEY='your_key'"
        )
    return key


def _vt_request(endpoint: str, api_key: str) -> dict:
    url = f"{VT_API_BASE}{endpoint}"
    req = urllib.request.Request(url, headers={"x-apikey": api_key})
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise VTSyncError(f"Failed to connect to VirusTotal API: {exc}")


def sync_yara_rules(output_dir: Path | None = None, limit: int = 20) -> int:
    """Fetches the latest YARA rules from VT and saves them locally."""
    api_key = get_api_key()
    out_dir = Path(output_dir) if output_dir else DEFAULT_SYNC_DIR / "yara"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    out_file = out_dir / "vt_synced_rules.yar"
    
    print(f"[*] Fetching up to {limit} YARA rules from VirusTotal...")
    data = _vt_request(f"/yara_rules?limit={limit}", api_key)
    
    rules = data.get("data", [])
    if not rules:
        print("[-] No YARA rules found in VT response.")
        return 0

    valid_rules = 0
    with out_file.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by PCAPCase VT-Sync\n")
        f.write("// Source: VirusTotal YARA Rules API\n\n")
        
        for item in rules:
            attr = item.get("attributes", {})
            rule_text = attr.get("rule")
            if rule_text:
                f.write(f"// Rule: {attr.get('name', 'Unknown')}\n")
                f.write(f"// Author: {attr.get('author', 'Unknown')}\n")
                f.write(rule_text)
                f.write("\n\n")
                valid_rules += 1
                
    print(f"[+] Successfully synced {valid_rules} YARA rules.")
    print(f"[+] Saved to: {out_file}")
    print(f"[i] To use these rules in analysis, run:")
    print(f"    pcapcase analyze incident.pcap --extract-http --yara-rules {out_dir}")
    
    return valid_rules

