from __future__ import annotations

from html import escape
from pathlib import Path

from pcapcase.models import format_datetime
from pcapcase.report import ReportData


def render(data: ReportData) -> str:
    case = data.case
    parts: list[str] = []
    parts.append("<!doctype html>")
    parts.append('<html lang="en"><head><meta charset="utf-8">')
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append(f"<title>PCAPCase Report: {escape(Path(case.capture.path).name)}</title>")
    parts.append("<style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;margin:2rem;line-height:1.5;color:#17202a}code,pre{background:#f4f6f8;padding:.15rem .3rem;border-radius:4px}pre{padding:1rem;overflow:auto}table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #d8dee4;padding:.4rem;text-align:left;vertical-align:top}.sev-critical,.sev-high{color:#9f1239}.sev-medium{color:#b45309}.sev-low{color:#0369a1}.sev-info{color:#475569}.card{border:1px solid #d8dee4;border-radius:8px;padding:1rem;margin:1rem 0}</style>")
    parts.append("</head><body>")
    parts.append(f"<h1>PCAPCase Report: {escape(Path(case.capture.path).name)}</h1>")
    parts.append("<h2>Executive summary</h2>")
    parts.append(f"<p>PCAPCase analyzed <code>{escape(case.capture.path)}</code> and produced {len(case.events)} timeline events, {len(case.hosts)} hosts, {len(case.indicators)} indicators, {len(case.findings)} findings, and {len(case.extracted_objects)} extracted objects.</p>")
    parts.append("<h2>Capture details</h2>")
    parts.append("<table><tbody>")
    for key, value in [("SHA-256", case.capture.sha256), ("TShark", case.capture.tshark_version or "unknown"), ("Frames", str(case.capture.frame_count if case.capture.frame_count is not None else "unknown")), ("First seen", format_datetime(case.capture.first_seen) or "unknown"), ("Last seen", format_datetime(case.capture.last_seen) or "unknown")]:
        parts.append(f"<tr><th>{escape(key)}</th><td><code>{escape(value)}</code></td></tr>")
    parts.append("</tbody></table>")
    parts.append("<h2>Key findings</h2>")
    if not case.findings:
        parts.append("<p>No findings generated by enabled detectors.</p>")
    for finding in sorted(case.findings, key=lambda f: (f.severity, f.first_seen, f.id)):
        parts.append(f'<section class="card"><h3 class="sev-{escape(finding.severity)}">{escape(finding.severity.upper())}: {escape(finding.title)}</h3>')
        parts.append(f"<p><strong>Summary:</strong> {escape(finding.description)}</p>")
        parts.append("<table><tbody>")
        rows = [("First seen", format_datetime(finding.first_seen) or ""), ("Last seen", format_datetime(finding.last_seen) or ""), ("Source", ", ".join(finding.source_hosts) or "unknown"), ("Destination", ", ".join(finding.destination_hosts) or "unknown"), ("Confidence", finding.confidence)]
        for key, value in rows:
            parts.append(f"<tr><th>{escape(key)}</th><td>{escape(value)}</td></tr>")
        for mitre in finding.mitre_attack:
            value = f"{mitre.get('id', 'unknown')} — {mitre.get('name', 'unknown')} ({mitre.get('confidence', 'unknown')})"
            parts.append(f"<tr><th>MITRE ATT&amp;CK</th><td>{escape(value)}</td></tr>")
        parts.append("</tbody></table><h4>Evidence</h4><ul>")
        for evidence in finding.evidence:
            stream = evidence.tcp_stream if evidence.tcp_stream is not None else "n/a"
            parts.append(f"<li>frame <code>{evidence.frame_number}</code>, stream <code>{escape(str(stream))}</code>, <code>{escape(evidence.field)}</code> = <code>{escape(evidence.value)}</code></li>")
        parts.append("</ul><h4>Reproduce</h4><pre><code>")
        parts.append(escape(finding.evidence[0].reproduction_command if finding.evidence else "tshark -r <pcap>"))
        parts.append("</code></pre></section>")
    parts.append("<h2>Timeline summary</h2><ul>")
    for event in case.events[:25]:
        parts.append(f"<li><code>{escape(format_datetime(event.timestamp) or '')}</code> frame <code>{event.frame_number}</code> {escape(event.protocol.upper())} {escape(event.summary)}</li>")
    parts.append("</ul><h2>Host inventory</h2><table><thead><tr><th>IP</th><th>Protocols</th><th>Sent</th><th>Received</th></tr></thead><tbody>")
    for host in case.hosts:
        parts.append(f"<tr><td>{escape(host.ip)}</td><td>{escape(', '.join(host.protocols))}</td><td>{host.sent_events}</td><td>{host.received_events}</td></tr>")
    parts.append("</tbody></table><h2>Indicators of compromise</h2><table><thead><tr><th>Type</th><th>Value</th><th>First seen</th><th>Source</th></tr></thead><tbody>")
    for indicator in case.indicators[:100]:
        parts.append(f"<tr><td>{escape(indicator.type)}</td><td><code>{escape(indicator.value)}</code></td><td>{escape(format_datetime(indicator.first_seen) or '')}</td><td>{escape(indicator.source)}</td></tr>")
    parts.append("</tbody></table><h2>Extracted objects</h2>")
    if not case.extracted_objects:
        parts.append("<p>No extracted objects recorded.</p>")
    else:
        parts.append("<ul>")
        for obj in case.extracted_objects:
            parts.append(f"<li><code>{escape(obj.sanitized_filename)}</code> sha256=<code>{escape(obj.sha256)}</code> size={obj.size} bytes frame={escape(str(obj.source_frame or 'unknown'))} stream={escape(str(obj.tcp_stream or 'unknown'))}</li>")
        parts.append("</ul>")
    parts.append("<h2>Evidence and reproduction commands</h2><ul>")
    for finding in case.findings:
        for evidence in finding.evidence:
            parts.append(f"<li>{escape(finding.id)} frame {evidence.frame_number}: <code>{escape(evidence.reproduction_command)}</code></li>")
    parts.append("</ul><h2>Re-run manifest</h2>")
    if data.rerun_manifest:
        parts.append(f"<p>Manifest timestamp: <code>{escape(str(data.rerun_manifest.get('run_timestamp')))}</code></p>")
        parts.append(f"<p>CLI args: <code>{escape(' '.join(data.rerun_manifest.get('cli_args', [])))}</code></p>")
    else:
        parts.append("<p>No re-run manifest was attached.</p>")
    parts.append("<h2>Limitations</h2><p>Encrypted traffic limits visibility. NAT may hide host identity. Missing packets can break stream reconstruction. PCAPCase reports suspicious behavior, not final attribution.</p>")
    parts.append("<h2>Appendix: full timeline</h2><ul>")
    for event in case.events:
        parts.append(f"<li><code>{escape(format_datetime(event.timestamp) or '')}</code> frame <code>{event.frame_number}</code> {escape(event.src_ip or '')}:{escape(str(event.src_port or ''))} → {escape(event.dst_ip or '')}:{escape(str(event.dst_port or ''))} {escape(event.protocol)} {escape(event.summary)}</li>")
    parts.append("</ul></body></html>\n")
    return "".join(parts)


def write_report(path: str | Path, data: ReportData) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(data), encoding="utf-8")
