import json
from html import escape
from pathlib import Path

from pcapcase.models import format_datetime
from pcapcase.report import ReportData


def render(data: ReportData) -> str:
    case = data.case

    # Visualization Data Prep
    proto_counts = {}
    for event in case.events:
        p = event.protocol.upper()
        proto_counts[p] = proto_counts.get(p, 0) + 1
    proto_data = [{"name": k, "count": v} for k, v in sorted(proto_counts.items(), key=lambda x: x[1], reverse=True)]

    sorted_hosts = sorted(case.hosts, key=lambda h: h.sent_events + h.received_events, reverse=True)[:10]
    max_host_events = max((h.sent_events + h.received_events for h in sorted_hosts), default=1)
    
    bar_html = ""
    if sorted_hosts:
        for h in sorted_hosts:
            total_ev = h.sent_events + h.received_events
            pct = (total_ev / max_host_events) * 100 if max_host_events > 0 else 0
            bar_html += f'<div class="bar-row"><div class="bar-label" title="{escape(h.ip)}">{escape(h.ip)}</div><div class="bar-track"><div class="bar-fill" style="width: {pct}%;"></div></div><div class="bar-val">{total_ev}</div></div>'
    else:
        bar_html = "<p>No host data available.</p>"

    link_counts = {}
    for event in case.events:
        if event.src_ip and event.dst_ip:
            pair = (event.src_ip, event.dst_ip)
            link_counts[pair] = link_counts.get(pair, 0) + 1

    top_links = sorted(link_counts.items(), key=lambda x: x[1], reverse=True)[:100]
    unique_nodes = list(set([ip for pair, _ in top_links for ip in pair]))
    node_index = {ip: i for i, ip in enumerate(unique_nodes)}
    graph_nodes = unique_nodes
    graph_links = [{"src": node_index[pair[0]], "dst": node_index[pair[1]], "weight": count} for pair, count in top_links]

    # Findings HTML
    findings_html = ""
    if not case.findings:
        findings_html = "<p>No findings generated by enabled detectors.</p>"
    for finding in sorted(case.findings, key=lambda f: (f.severity, f.first_seen, f.id)):
        findings_html += f'<div class="card"><h3 style="margin-top:0"><span class="badge {escape(finding.severity)}">{escape(finding.severity)}</span> {escape(finding.title)}</h3>'
        findings_html += f"<p><strong>Summary:</strong> {escape(finding.description)}</p>"
        findings_html += "<table><tbody>"
        rows = [
            ("First seen", format_datetime(finding.first_seen) or ""), 
            ("Last seen", format_datetime(finding.last_seen) or ""), 
            ("Source", ", ".join(finding.source_hosts) or "unknown"), 
            ("Destination", ", ".join(finding.destination_hosts) or "unknown"), 
            ("Confidence", finding.confidence)
        ]
        for key, value in rows:
            findings_html += f"<tr><th>{escape(key)}</th><td>{escape(value)}</td></tr>"
        for mitre in finding.mitre_attack:
            val = f"{mitre.get('id', 'unknown')} — {mitre.get('name', 'unknown')} ({mitre.get('confidence', 'unknown')})"
            findings_html += f"<tr><th>MITRE ATT&amp;CK</th><td>{escape(val)}</td></tr>"
        findings_html += "</tbody></table><h4>Evidence</h4><ul>"
        for evidence in finding.evidence:
            stream = str(evidence.tcp_stream) if evidence.tcp_stream is not None else "n/a"
            findings_html += f"<li>Frame <code>{evidence.frame_number}</code>, stream <code>{escape(stream)}</code>, <code>{escape(evidence.field)}</code> = <code>{escape(evidence.value)}</code></li>"
        findings_html += "</ul><h4>Reproduce</h4><pre><code>"
        findings_html += escape(finding.evidence[0].reproduction_command if finding.evidence else "tshark -r <pcap>")
        findings_html += "</code></pre></div>"

    # Timeline HTML
    timeline_html = "<ul>"
    for event in case.events[:100]:
        timeline_html += f"<li><code>{escape(format_datetime(event.timestamp) or '')}</code> frame <code>{event.frame_number}</code> {escape(event.protocol.upper())} {escape(event.summary)}</li>"
    timeline_html += "</ul><p><em>Showing first 100 events. See timeline.csv for full data.</em></p>"

    # Hosts HTML
    hosts_html = "<table><thead><tr><th>IP</th><th>Protocols</th><th>Sent</th><th>Received</th></tr></thead><tbody>"
    for host in case.hosts:
        hosts_html += f"<tr><td>{escape(host.ip)}</td><td>{escape(', '.join(host.protocols))}</td><td>{host.sent_events}</td><td>{host.received_events}</td></tr>"
    hosts_html += "</tbody></table>"

    # IOCs HTML
    iocs_html = "<table><thead><tr><th>Type</th><th>Value</th><th>First seen</th><th>Source</th></tr></thead><tbody>"
    for indicator in case.indicators[:100]:
        iocs_html += f"<tr><td>{escape(indicator.type)}</td><td><code>{escape(indicator.value)}</code></td><td>{escape(format_datetime(indicator.first_seen) or '')}</td><td>{escape(indicator.source)}</td></tr>"
    iocs_html += "</tbody></table><p><em>Showing first 100 IOCs. See iocs.json for full data.</em></p>"

    # Objects HTML
    objects_html = ""
    if not case.extracted_objects:
        objects_html = "<p>No extracted objects recorded.</p>"
    else:
        objects_html = "<ul>"
        for obj in case.extracted_objects:
            objects_html += f"<li><code>{escape(obj.sanitized_filename)}</code> sha256=<code>{escape(obj.sha256)}</code> size={obj.size} bytes frame={escape(str(obj.source_frame or 'unknown'))} stream={escape(str(obj.tcp_stream or 'unknown'))}</li>"
        objects_html += "</ul>"

    manifest_html = ""
    if data.rerun_manifest:
        manifest_html = f"<p>Manifest timestamp: <code>{escape(str(data.rerun_manifest.get('run_timestamp')))}</code><br>CLI args: <code>{escape(' '.join(data.rerun_manifest.get('cli_args', [])))}</code></p>"
    else:
        manifest_html = "<p>No re-run manifest attached.</p>"

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PCAPCase Report: {escape(Path(case.capture.path).name)}</title>
<style>
  :root {{ --bg: #f8f9fa; --border: #dee2e6; --primary: #0d6efd; --text: #212529; --text-muted: #6c757d; }}
  body {{ margin: 0; display: flex; height: 100vh; font-family: system-ui, -apple-system, sans-serif; color: var(--text); overflow: hidden; }}
  aside {{ width: 260px; min-width: 260px; background: var(--bg); border-right: 1px solid var(--border); display: flex; flex-direction: column; overflow-y: auto; }}
  aside h2 {{ font-size: 1.2rem; padding: 1.25rem 1rem; margin: 0; border-bottom: 1px solid var(--border); background: #fff; position: sticky; top: 0; z-index: 10; }}
  .nav-menu {{ list-style: none; padding: 0; margin: 0; }}
  .nav-item {{ padding: 0.85rem 1rem; cursor: pointer; border-bottom: 1px solid #f1f3f5; font-size: 0.95rem; transition: background 0.2s; }}
  .nav-item:hover {{ background: #e9ecef; }}
  .nav-item.active {{ background: var(--primary); color: white; font-weight: 500; border-bottom-color: var(--primary); }}
  .badge-pill {{ float: right; background: rgba(0,0,0,0.1); padding: 0.1rem 0.5rem; border-radius: 12px; font-size: 0.8rem; }}
  .nav-item.active .badge-pill {{ background: rgba(255,255,255,0.2); }}
  
  main {{ flex: 1; padding: 2rem; overflow-y: auto; background: #ffffff; }}
  .section {{ display: none; max-width: 1000px; margin: 0 auto; }}
  .section.active {{ display: block; }}
  h1 {{ font-size: 1.8rem; margin-top: 0; border-bottom: 2px solid var(--bg); padding-bottom: 0.5rem; }}
  h3 {{ margin-top: 1.5rem; margin-bottom: 1rem; }}
  
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }}
  th, td {{ border: 1px solid var(--border); padding: 0.6rem; text-align: left; vertical-align: top; }}
  th {{ background: var(--bg); font-weight: 600; width: 25%; }}
  
  .card {{ border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }}
  .badge {{ display: inline-block; padding: 0.25rem 0.6rem; border-radius: 4px; font-size: 0.75rem; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }}
  .critical {{ background: #9f1239; color: white; }}
  .high {{ background: #e11d48; color: white; }}
  .medium {{ background: #f59e0b; color: white; }}
  .low {{ background: #0ea5e9; color: white; }}
  .info {{ background: #64748b; color: white; }}
  
  pre, code {{ background: #f1f3f5; padding: 0.2rem 0.4rem; border-radius: 4px; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 0.85rem; word-break: break-all; }}
  pre {{ padding: 1rem; overflow-x: auto; word-break: normal; }}
  
  /* Visualizations */
  .grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem; }}
  .chart-container {{ border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }}
  .chart-container h3 {{ margin-top: 0; text-align: left; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  
  .bar-row {{ display: flex; align-items: center; margin-bottom: 0.75rem; font-size: 0.85rem; }}
  .bar-label {{ width: 140px; text-align: left; padding-right: 1rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
  .bar-track {{ flex: 1; background: #e9ecef; height: 16px; border-radius: 4px; overflow: hidden; }}
  .bar-fill {{ height: 100%; background: var(--primary); transition: width 0.5s ease-in-out; }}
  .bar-val {{ width: 50px; text-align: right; padding-left: 0.5rem; font-weight: 500; color: var(--text-muted); }}
  
  .graph-container {{ border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.02); overflow: hidden; }}
  .graph-container h3 {{ margin-top: 0; text-align: left; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  canvas {{ max-width: 100%; height: auto; }}
</style>
</head>
<body>
  <aside>
    <h2>PCAPCase</h2>
    <ul class="nav-menu">
      <li class="nav-item active" onclick="show('summary', this)">Executive Summary</li>
      <li class="nav-item" onclick="show('visuals', this)">Visualizations</li>
      <li class="nav-item" onclick="show('findings', this)">Findings <span class="badge-pill">{len(case.findings)}</span></li>
      <li class="nav-item" onclick="show('timeline', this)">Timeline <span class="badge-pill">{len(case.events)}</span></li>
      <li class="nav-item" onclick="show('hosts', this)">Host Inventory <span class="badge-pill">{len(case.hosts)}</span></li>
      <li class="nav-item" onclick="show('iocs', this)">IOCs <span class="badge-pill">{len(case.indicators)}</span></li>
      <li class="nav-item" onclick="show('objects', this)">Extracted Objects <span class="badge-pill">{len(case.extracted_objects)}</span></li>
    </ul>
  </aside>
  <main>
    <div id="summary" class="section active">
      <h1>Executive Summary</h1>
      <p>PCAPCase analyzed <code>{escape(case.capture.path)}</code> and generated evidence-backed artifacts.</p>
      
      <h3>Capture Details</h3>
      <table>
        <tbody>
          <tr><th>File Name</th><td><code>{escape(Path(case.capture.path).name)}</code></td></tr>
          <tr><th>SHA-256</th><td><code>{escape(case.capture.sha256)}</code></td></tr>
          <tr><th>TShark Engine</th><td><code>{escape(case.capture.tshark_version or 'unknown')}</code></td></tr>
          <tr><th>Total Frames</th><td><code>{case.capture.frame_count if case.capture.frame_count is not None else 'unknown'}</code></td></tr>
          <tr><th>First Seen (UTC)</th><td>{escape(format_datetime(case.capture.first_seen) or 'unknown')}</td></tr>
          <tr><th>Last Seen (UTC)</th><td>{escape(format_datetime(case.capture.last_seen) or 'unknown')}</td></tr>
        </tbody>
      </table>

      <h3>Re-run Manifest</h3>
      {manifest_html}

      <h3>Limitations</h3>
      <p style="color: var(--text-muted); font-size: 0.9rem; line-height: 1.6;">
        Encrypted traffic limits visibility. NAT may hide host identity. Missing packets can break stream reconstruction. 
        PCAPCase reports suspicious behavior based on packet heuristics, not final attribution.
      </p>
    </div>
    
    <div id="visuals" class="section">
      <h1>Visualizations</h1>
      <div class="grid-2">
        <div class="chart-container">
          <h3>Protocol Distribution</h3>
          <canvas id="pieChart" width="300" height="300"></canvas>
        </div>
        <div class="chart-container">
          <h3>Top Active Hosts (By Event Count)</h3>
          <div style="margin-top: 1.5rem;">
            {bar_html}
          </div>
        </div>
      </div>
      <div class="graph-container">
        <h3>Network Connections Graph</h3>
        <p style="font-size: 0.85rem; color: var(--text-muted); text-align: left; margin-top: 0;">Mapping up to top 100 connection pairs</p>
        <canvas id="netGraph" width="800" height="600" style="background: #fafafa; border-radius: 4px; border: 1px solid #eee;"></canvas>
      </div>
    </div>
    
    <div id="findings" class="section">
      <h1>Findings</h1>
      {findings_html}
    </div>
    
    <div id="timeline" class="section">
      <h1>Timeline</h1>
      {timeline_html}
    </div>
    
    <div id="hosts" class="section">
      <h1>Host Inventory</h1>
      {hosts_html}
    </div>
    
    <div id="iocs" class="section">
      <h1>Indicators of Compromise (IOCs)</h1>
      {iocs_html}
    </div>
    
    <div id="objects" class="section">
      <h1>Extracted Objects</h1>
      {objects_html}
    </div>
  </main>
  
  <script>
    function show(id, element) {{
       document.querySelectorAll('.section').forEach(el => el.classList.remove('active'));
       document.querySelectorAll('.nav-item').forEach(el => el.classList.remove('active'));
       document.getElementById(id).classList.add('active');
       element.classList.add('active');
    }}

    const protoData = {json.dumps(proto_data)};
    const graphNodes = {json.dumps(graph_nodes)};
    const graphLinks = {json.dumps(graph_links)};

    window.onload = function() {{
        // Pie Chart Rendering (Donut style)
        const pie = document.getElementById('pieChart');
        if(pie && protoData.length > 0) {{
            const ctx = pie.getContext('2d');
            const cx = 150, cy = 150, r = 100;
            let start = 0;
            const colors = ['#0d6efd', '#198754', '#dc3545', '#ffc107', '#0dcaf0', '#6f42c1', '#d63384', '#fd7e14'];
            const total = protoData.reduce((acc, v) => acc + v.count, 0);
            
            let legendY = 10;
            
            protoData.forEach((d, i) => {{
                const slice = (d.count / total) * 2 * Math.PI;
                ctx.beginPath();
                ctx.moveTo(cx, cy);
                ctx.arc(cx, cy, r, start, start + slice);
                ctx.fillStyle = colors[i % colors.length];
                ctx.fill();
                
                if (i < 8) {{
                    ctx.fillRect(10, legendY, 12, 12);
                    ctx.fillStyle = '#212529';
                    ctx.font = '12px system-ui, sans-serif';
                    ctx.fillText(d.name + ' (' + d.count + ')', 28, legendY + 11);
                    legendY += 20;
                }}
                start += slice;
            }});
            
            // Inner circle for donut
            ctx.beginPath();
            ctx.arc(cx, cy, r * 0.5, 0, 2 * Math.PI);
            ctx.fillStyle = '#fff';
            ctx.fill();
        }}

        // Network Graph Rendering
        const net = document.getElementById('netGraph');
        if(net && graphNodes.length > 0) {{
            const ctx = net.getContext('2d');
            const width = net.width, height = net.height;
            const cx = width/2, cy = height/2, r = Math.min(width, height)/2 - 60;
            
            const nodes = graphNodes.map((ip, i) => {{
                const angle = (i / graphNodes.length) * 2 * Math.PI;
                return {{ ip: ip, x: cx + r * Math.cos(angle), y: cy + r * Math.sin(angle) }};
            }});

            ctx.lineWidth = 1.5;
            graphLinks.forEach(link => {{
                const n1 = nodes[link.src];
                const n2 = nodes[link.dst];
                ctx.beginPath();
                ctx.moveTo(n1.x, n1.y);
                ctx.lineTo(n2.x, n2.y);
                const opacity = Math.min(0.2 + (link.weight * 0.05), 0.8);
                ctx.strokeStyle = `rgba(13, 110, 253, ${{opacity}})`;
                ctx.stroke();
            }});

            nodes.forEach(n => {{
                ctx.beginPath();
                ctx.arc(n.x, n.y, 6, 0, 2*Math.PI);
                ctx.fillStyle = '#dc3545';
                ctx.fill();
                ctx.strokeStyle = '#fff';
                ctx.lineWidth = 2;
                ctx.stroke();
                
                ctx.fillStyle = '#212529';
                ctx.font = '11px system-ui, sans-serif';
                
                const textWidth = ctx.measureText(n.ip).width;
                let tx = n.x, ty = n.y;
                if (n.x > cx) tx += 10; else tx -= (textWidth + 10);
                if (n.y > cy) ty += 10; else ty -= 10;
                ctx.fillText(n.ip, tx, ty);
            }});
        }}
    }};
  </script>
</body>
</html>"""
    return html


def write_report(path: str | Path, data: ReportData) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(data), encoding="utf-8")