from __future__ import annotations

from pathlib import Path

from pcapcase.models import CaseResult, format_datetime
from pcapcase.report import ReportData


def render(data: ReportData) -> str:
    case = data.case
    lines: list[str] = []
    lines.append(f"# PCAPCase Report: {Path(case.capture.path).name}")
    lines.append("")
    lines.append("## Executive summary")
    lines.append("")
    lines.append(f"PCAPCase analyzed `{case.capture.path}` and produced {len(case.events)} timeline events, {len(case.hosts)} hosts, {len(case.indicators)} indicators, {len(case.findings)} findings, and {len(case.extracted_objects)} extracted objects.")
    lines.append("")
    lines.append("## Capture details")
    lines.append("")
    lines.extend([
        f"- SHA-256: `{case.capture.sha256}`",
        f"- TShark: `{case.capture.tshark_version or 'unknown'}`",
        f"- Frames: `{case.capture.frame_count if case.capture.frame_count is not None else 'unknown'}`",
        f"- First seen: `{format_datetime(case.capture.first_seen) or 'unknown'}`",
        f"- Last seen: `{format_datetime(case.capture.last_seen) or 'unknown'}`",
    ])
    lines.append("")
    lines.append("## Key findings")
    lines.append("")
    if not case.findings:
        lines.append("No findings generated by enabled detectors.")
    for finding in sorted(case.findings, key=lambda f: (f.severity, f.first_seen, f.id)):
        lines.append(f"### {finding.severity.upper()}: {finding.title}")
        lines.append("")
        lines.append(f"**Summary:** {finding.description}")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("| --- | --- |")
        lines.append(f"| First seen | {format_datetime(finding.first_seen)} |")
        lines.append(f"| Last seen | {format_datetime(finding.last_seen)} |")
        lines.append(f"| Source | {', '.join(finding.source_hosts) or 'unknown'} |")
        lines.append(f"| Destination | {', '.join(finding.destination_hosts) or 'unknown'} |")
        lines.append(f"| Confidence | {finding.confidence} |")
        if finding.mitre_attack:
            for mitre in finding.mitre_attack:
                lines.append(f"| MITRE ATT&CK | {mitre.get('id', 'unknown')} — {mitre.get('name', 'unknown')} ({mitre.get('confidence', 'unknown')}) |")
        lines.append("")
        lines.append("**Evidence:**")
        lines.append("")
        for evidence in finding.evidence:
            lines.append(f"- frame `{evidence.frame_number}`, stream `{evidence.tcp_stream if evidence.tcp_stream is not None else 'n/a'}`, `{evidence.field}` = `{evidence.value}`")
        lines.append("")
        lines.append("**Reproduce:**")
        lines.append("")
        lines.append("```bash")
        lines.append(finding.evidence[0].reproduction_command if finding.evidence else "tshark -r <pcap>")
        lines.append("```")
        lines.append("")
    lines.append("## Timeline summary")
    lines.append("")
    for event in case.events[:25]:
        lines.append(f"- `{format_datetime(event.timestamp)}` frame `{event.frame_number}` {event.protocol.upper()} {event.summary}")
    lines.append("")
    lines.append("## Host inventory")
    lines.append("")
    lines.append("| IP | Protocols | Sent | Received |")
    lines.append("| --- | --- | ---: | ---: |")
    for host in case.hosts:
        lines.append(f"| {host.ip} | {', '.join(host.protocols)} | {host.sent_events} | {host.received_events} |")
    lines.append("")
    lines.append("## Indicators of compromise")
    lines.append("")
    lines.append("| Type | Value | First seen | Source |")
    lines.append("| --- | --- | --- | --- |")
    for indicator in case.indicators[:100]:
        lines.append(f"| {indicator.type} | `{indicator.value}` | {format_datetime(indicator.first_seen)} | {indicator.source} |")
    lines.append("")
    lines.append("## Extracted objects")
    lines.append("")
    if not case.extracted_objects:
        lines.append("No extracted objects recorded.")
    for obj in case.extracted_objects:
        lines.append(f"- `{obj.sanitized_filename}` sha256=`{obj.sha256}` size={obj.size} bytes frame={obj.source_frame or 'unknown'} stream={obj.tcp_stream or 'unknown'}")
    lines.append("")
    lines.append("## Evidence and reproduction commands")
    lines.append("")
    for finding in case.findings:
        for evidence in finding.evidence:
            lines.append(f"- {finding.id} frame {evidence.frame_number}: `{evidence.reproduction_command}`")
    lines.append("")
    lines.append("## Re-run manifest")
    lines.append("")
    if data.rerun_manifest:
        lines.append(f"- Manifest timestamp: `{data.rerun_manifest.get('run_timestamp')}`")
        lines.append(f"- CLI args: `{' '.join(data.rerun_manifest.get('cli_args', []))}`")
    else:
        lines.append("No re-run manifest was attached.")
    lines.append("")
    lines.append("## Limitations")
    lines.append("")
    lines.append("Encrypted traffic limits visibility. NAT may hide host identity. Missing packets can break stream reconstruction. PCAPCase reports suspicious behavior, not final attribution.")
    lines.append("")
    lines.append("## Appendix: full timeline")
    lines.append("")
    for event in case.events:
        lines.append(f"- `{format_datetime(event.timestamp)}` frame `{event.frame_number}` {event.src_ip or ''}:{event.src_port or ''} → {event.dst_ip or ''}:{event.dst_port or ''} {event.protocol} {event.summary}")
    lines.append("")
    return "\n".join(lines)


def write_report(path: str | Path, data: ReportData) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(data), encoding="utf-8")
